site_name: 資安防護基礎教材 | Shield of Self-Defense (SSD)
site_url: https://ssd.ocf.tw/
site_description: "給公民團體 CSOs 的資安防護基礎教材"
site_author: "財團法人開放文化基金會 (Open Culture Foundation, OCF)"
copyright: "CC-BY 4.0 姓名標示"
nav:
  - 課程主題:
      - chapter/index.md
      - 威脅建模:
          - chapter/threat/index.md
          - 建立威脅模型: user_guide/risk_assessment.md
      - 裝置安全:
          - chapter/devices/index.md
          - 裝置物理防護: user_guide/devices/index.md
          - iOS 裝置設定: user_guide/devices/ios.md
          - MacOS: user_guide/devices/macOS.md
          - Windows: user_guide/devices/windows.md
          - Android: user_guide/devices/android.md
      - 身分驗證:
          - chapter/profile/index.md
          - 密碼管理器: chapter/profile/password_manager.md
          - 密碼強度: chapter/profile/password.md
          - 多因子驗證: chapter/profile/mfa.md
      - 網路使用行為:
          - chapter/network/index.md
          - 隱私瀏覽行為: chapter/network/browser_privacy.md
          - 釣魚、詐騙: chapter/network/phishing.md
          - VPN: chapter/network/vpn.md
          - 網路與 Wi-Fi: chapter/network/wifi.md
      - 加密通訊:
          - chapter/e2ee/index.md
          - 加密即時通訊: chapter/e2ee/im.md
          - 加密電子郵件: chapter/e2ee/mails.md
      - 帳號管理:
          - chapter/account/index.md
          - 帳號管理原則: chapter/account/management.md
          - Google Workspace 管理: user_guide/account/management.md
      - 資料管理與備份:
          - chapter/files_management/index.md
          - 檔案存取權限: chapter/files_management/files_access.md
          - 資料備份與封存: chapter/files_management/backup_archive.md
          - NAS 安裝與設定: user_guide/files_management/backup_archive.md
          - 更新軟體: chapter/files_management/software_update.md
      - 海外出差:
          - chapter/abroad/index.md
          - 如何評估出差風險:
              - user_guide/abroad/index.md
  - 資安工作守則:
      - policy/index.md
      - 威脅建模: chapter/threat/policy.md
      - 裝置安全: chapter/devices/policy.md
      - 身分驗證: chapter/profile/policy.md
      - 網路使用行為: chapter/network/policy.md
      - 加密通訊: chapter/e2ee/policy.md
      - 帳號管理: chapter/account/policy.md
      - 資料管理與備份: chapter/files_management/policy.md
      - 海外出差: chapter/abroad/policy.md
  - 進度追蹤:
      - assessment/index.md
      - 檢查清單:
          - assessment/checklist/index.md
          - 場勘紀錄表: assessment/checklist/site_survey.md
          - 課後任務清單: assessment/checklist/homework.md
  - 工具推薦:
      - tools/index.md
  - 學習資源:
      - resource/index.md
  - 疑問諮詢:
      - support/index.md
  - 資安通報:
      - help/index.md
  - 如何貢獻:
      - contribute/index.md
  - 資安提升計畫:
      - guide/index.md
      - guide/status.md
      - guide/assessment.md
      - guide/initial-improvement.md
      - 裝置安全:
          - guide/devices/index.md
          - guide/devices/checklists.md
      - guide/profile.md
      - guide/network.md
      - guide/e2ee.md
      - guide/account.md
      - guide/files-management.md
      - guide/abroad.md
theme:
  name: material
  icon:
    logo: material/security
  favicon: asserts/security.svg
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 自動偵測模式
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: pink
      toggle:
        icon: material/weather-sunny
        name: 切換到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: yellow
      toggle:
        icon: material/weather-night
        name: 切換到明亮模式
  language: zh-TW
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.path
    - content.tooltips
  custom_dir: overrides
plugins:
  - search:
      pipeline:
        - stemmer
        - stopWordFilter
        - trimmer
      lang:
        - en
        - zh
  - offline
  - privacy
  - social:
      cards_layout_options:
        font_family: Noto Sans TC
  - git-revision-date-localized:
      type: iso_datetime
      timezone: Asia/Taipei
      enable_creation_date: true
      enable_parallel_processing: true
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.tabbed:
      alternate_style: true
extra:
  analytics:
    provider: google
    property: G-X3DG2E5E3W
  social:
    - icon: material/home
      link: https://ssd.ocf.tw/
    - icon: fontawesome/brands/github
      link: https://github.com/ocftw/ssd
    - icon: simple/torbrowser
      link: http://ssdocftwvq6csls7gnjubyrmar7no7ww3gmgodhznxgsoor6ot42lrad.onion/
extra_css:
  - stylesheets/extra.css
