name: Build Docs
on:
  push:
    branches:
      - shield
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name ocf-ssd[bot]
          git config user.email ssd+bot@ocf.tw
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Cache Poetry venv
        uses: actions/cache@v4
        with:
          path: ./.venv
          key: poetry-venv-${{ hashFiles('**/poetry.lock') }}
      - name: Cache Poetry local
        uses: actions/cache@v4
        with:
          path: ~/.local/share/pypoetry
          key: poetry-local-${{ hashFiles('**/poetry.lock') }}
      - name: Cache Poetry cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: poetry-cache-${{ hashFiles('**/poetry.lock') }}
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Install dependencies
        run: poetry install
      - name: Build Docs
        run: poetry run mkdocs gh-deploy --force
